//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONICAirlinesApp.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Schedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedules()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int AircraftID { get; set; }
        public int RouteID { get; set; }
        public decimal EconomyPrice { get; set; }
        public bool Confirmed { get; set; }
        public string FlightNumber { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
        public virtual Routes Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }

        [NotMapped]
        public int DepartureAirportID =>
            AMONICEntities.GetContext().Routes.
            FirstOrDefault(x => x.ID == RouteID).
            DepartureAirportID;

        [NotMapped]
        public int ArrivalAirportID =>
            AMONICEntities.GetContext().Routes.
            FirstOrDefault(x => x.ID == RouteID).
            ArrivalAirportID;

        [NotMapped]
        public string DepartureAirport => 
            AMONICEntities.GetContext().Airports.
            FirstOrDefault(x => x.ID == DepartureAirportID).
            IATACode;

        [NotMapped]
        public string ArrivalAirport =>
            AMONICEntities.GetContext().Airports.
            FirstOrDefault(x => x.ID == ArrivalAirportID).
            IATACode;

        [NotMapped]
        public int BussinesPrice => (int)((Double)EconomyPrice * 1.35);

        [NotMapped]
        public int FirstClassPrice => (int)((Double)BussinesPrice * 1.3);

        [NotMapped]
        public string StringDate => Date.ToString("d");
    }
}
