//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONICAirlinesApp.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserActivity
    {
        public System.DateTime Date { get; set; }
        public System.TimeSpan LoginTime { get; set; }
        public System.TimeSpan LogoutTime { get; set; }
        public string Error { get; set; }
        public int UserID { get; set; }
        public int ID { get; set; }
    
        public virtual Users Users { get; set; }

        [NotMapped]
        public string DateString => Date.Date.ToString("d");
        [NotMapped]
        public string SpentTime => (LogoutTime - LoginTime).ToString(@"hh\:mm\:ss");
        [NotMapped]
        public string LoginTimeString => LoginTime.ToString(@"hh\:mm\:ss");
        [NotMapped]
        public string LogoutTimeString => LogoutTime.ToString(@"hh\:mm\:ss");
    }
}
